// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zznsxkeyplpauggqabab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6bnN4a2V5cGxwYXVnZ3FhYmFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDk3NTQsImV4cCI6MjA3MzUyNTc1NH0.c1WCx3UCH5bgaI0K5BUDR4fBNw-pOBD_ZfJvCakM6AM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});